#!/usr/bin/env python3
"""Install NeuroClaw as an external-agent skill pack.

This installer creates a small "router skill" plus generated references. The
router skill gives the host agent a NeuroClaw persona and points it to the
local NeuroClaw repository for concrete neuroimaging, NeuroOracle, NeuroBench,
and model execution workflows.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).parent.parent.resolve()
SKILLS_ROOT = REPO_ROOT / "skills"
NEUROBENCH_ROOT = REPO_ROOT / "neurobench"
NEUROORACLE_ROOT = REPO_ROOT / "neurooracle"
MODELS_ROOT = REPO_ROOT / "models"
TASK_ATLAS = NEUROBENCH_ROOT / "task_atlas.json"

GENERATED_MARKER = "<!-- Generated by NeuroClaw installer/install_agent_integration.py -->"


@dataclass(frozen=True)
class InstallTarget:
    name: str
    root: Path


AGENT_TARGETS = [
    "codex",
    "claude-code",
    "cursor",
    "openclaw",
    "hermes",
    "workbuddy",
    "qclaw",
]


def _repo_path(path: Path) -> str:
    try:
        return str(path.resolve())
    except Exception:
        return str(path)


def _read_text(path: Path, max_chars: int | None = None) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return ""
    if max_chars is not None and len(text) > max_chars:
        return text[:max_chars].rstrip() + "\n..."
    return text


def _strip_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, flags=re.DOTALL)
    if not match:
        return {}, text
    meta: dict[str, str] = {}
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if not line or ":" not in line:
            continue
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip("\"'")
    return meta, text[match.end() :]


def _first_heading_or_sentence(body: str) -> str:
    for line in body.splitlines():
        clean = line.strip(" #\t")
        if clean and not clean.startswith("```"):
            return clean[:180]
    compact = re.sub(r"\s+", " ", body).strip()
    return compact[:180]


def _discover_skills() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    if not SKILLS_ROOT.exists():
        return items
    for skill_md in sorted(SKILLS_ROOT.glob("*/SKILL.md")):
        raw = _read_text(skill_md, max_chars=12000)
        meta, body = _strip_frontmatter(raw)
        name = meta.get("name") or skill_md.parent.name
        desc = meta.get("description") or _first_heading_or_sentence(body)
        items.append(
            {
                "name": name,
                "description": desc,
                "path": _repo_path(skill_md),
                "folder": skill_md.parent.name,
            }
        )
    return items


def _write_skill_catalog(ref_dir: Path) -> None:
    skills = _discover_skills()
    lines = [
        GENERATED_MARKER,
        "# NeuroClaw Skill Catalog",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"Repository: `{_repo_path(REPO_ROOT)}`",
        f"Skill root: `{_repo_path(SKILLS_ROOT)}`",
        "",
        "Use this catalog first. Read the full SKILL.md only for the selected workflow.",
        "",
        "| Skill | Description | Source |",
        "|---|---|---|",
    ]
    for item in skills:
        desc = item["description"].replace("|", "\\|")
        lines.append(f"| `{item['name']}` | {desc} | `{item['path']}` |")
    if not skills:
        lines.append("| - | No skills discovered. | - |")
    _write_generated(ref_dir / "skill_catalog.md", "\n".join(lines) + "\n")


def _write_neurobench_catalog(ref_dir: Path) -> None:
    lines = [
        GENERATED_MARKER,
        "# NeuroBench Catalog",
        "",
        f"Repository: `{_repo_path(REPO_ROOT)}`",
        f"NeuroBench root: `{_repo_path(NEUROBENCH_ROOT)}`",
        "",
        "NeuroBench evaluates whether an agent can execute neuroimaging workflows,",
        "model training, and cross-model evaluation tasks.",
        "",
        "Common commands:",
        "",
        "```bash",
        "python core/agent/main.py --benchmark",
        "python core/agent/main.py --benchmark --benchmark-compare-skills",
        "python core/agent/main.py --score-benchmark",
        "```",
        "",
    ]
    try:
        atlas = json.loads(TASK_ATLAS.read_text(encoding="utf-8"))
    except Exception:
        atlas = {}
    categories = (
        atlas.get("operational_layer", {})
        .get("categories", {})
        if isinstance(atlas, dict)
        else {}
    )
    if isinstance(categories, dict) and categories:
        lines.extend(["## Categories", ""])
        for key, data in categories.items():
            if not isinstance(data, dict):
                continue
            label = data.get("label", key)
            summary = data.get("summary", "")
            tasks = data.get("tasks", [])
            lines.append(f"### {label} (`{key}`)")
            if summary:
                lines.append(str(summary))
            if isinstance(tasks, list):
                preview = ", ".join(f"`{t}`" for t in tasks[:12])
                suffix = " ..." if len(tasks) > 12 else ""
                lines.append(f"Tasks: {preview}{suffix}")
            lines.append("")
    _write_generated(ref_dir / "neurobench_catalog.md", "\n".join(lines) + "\n")


def _write_autoresearch_reference(ref_dir: Path) -> None:
    text = f"""{GENERATED_MARKER}
# NeuroClaw AutoResearch Reference

Repository: `{_repo_path(REPO_ROOT)}`
NeuroOracle root: `{_repo_path(NEUROORACLE_ROOT)}`

Use this reference when the user asks for NeuroOracle, knowledge graph search,
hypothesis generation, novelty checking, critic review, plausibility scoring, or
case-study autoresearch.

## Recommended Workflow

Prefer the case-study-driven autoresearch route when a graph already exists:

```bash
bash neurooracle/run_case_study.sh case1_transdiagnostic
bash neurooracle/run_case_study.sh case2_pathway_mediation
```

Or call the CLI directly:

```bash
python -m neurooracle.src.hypothesis_cli --graph <graph.json> case-study <case_id> --output-dir <runs/case_id>
```

## Host-Agent AutoResearch

Use this when the host agent should replace the configured LLM API with its own
built-in model for hypothesis generation, critic review, experiment
supervision, and next-round planning.

```bash
python -m neurooracle.src.hypothesis_cli host-agent-init case1_transdiagnostic --output-dir <runs/host_agent_case1> --max-rounds 5
```

Then the host agent should:

1. Read `<runs/host_agent_case1>/tasks/round_001_task.json`.
2. Use its own reasoning model to act as NeuroClaw's generator, critic, and
   experiment supervisor.
3. Run the deterministic NeuroOracle command in the task file when useful.
4. Write JSON to the task's `expected_result_path`.
5. Run:

```bash
python -m neurooracle.src.hypothesis_cli host-agent-next --run-dir <runs/host_agent_case1>
```

Repeat until `run_state.json` is `complete` or `blocked`.

## Graph Build And Claim Extraction

Use these only when the user needs to rebuild or refresh the knowledge graph:

```bash
python -m neurooracle.phase1
python -m neurooracle.phase2 --broad --max-workers 12
python -m neurooracle.phase2 --diseases "Alzheimer's disease" --year-start 2025 --year-end 2025
```

## Agent Behavior

- Treat the graph as the source of structured neuroscience evidence.
- Prefer registered case studies over open-ended free generation.
- Preserve outputs, logs, graph paths, hypotheses, critic feedback, novelty, and
  plausibility scores in a run directory.
- Before launching long jobs, inspect the selected script and explain expected
  inputs, outputs, and runtime assumptions.
- Do not fabricate PubMed evidence or KG edges. If inputs are missing, say what
  graph, abstracts, or case-study files are required.
"""
    _write_generated(ref_dir / "autoresearch.md", text)


def _write_host_agent_autoresearch_reference(ref_dir: Path) -> None:
    text = f"""{GENERATED_MARKER}
# NeuroClaw Host-Agent AutoResearch

Use this reference when Codex, Claude Code, Cursor, OpenClaw, Hermes,
WorkBuddy, or QClaw should use its own built-in model instead of a configured
LLM API for NeuroClaw autoresearch.

## Core Idea

The host agent is the reasoning backend. NeuroClaw provides the repository,
knowledge graph, NeuroOracle commands, NeuroBench checks, task files, result
schemas, and run-state validation.

Do not try to call the host agent as a Python API. Instead, run a file-based
loop:

1. NeuroClaw creates a JSON task.
2. The host agent reads the task and uses its own model to reason.
3. The host agent runs local NeuroClaw commands when useful.
4. The host agent writes a JSON result.
5. NeuroClaw validates the result and creates the next task.

## Start A Run

```bash
python -m neurooracle.src.hypothesis_cli host-agent-init case1_transdiagnostic --output-dir neurooracle/data/host_agent_runs/case1 --max-rounds 5
```

Optional:

```bash
python -m neurooracle.src.hypothesis_cli host-agent-init case2_pathway_mediation --output-dir neurooracle/data/host_agent_runs/case2 --deterministic-stages batch,novelty
```

## Per-Round Loop

For each round:

1. Read `run_state.json` and the current `tasks/round_XXX_task.json`.
2. Inspect or run the task's `deterministic_neurooracle_command`.
3. Act as:
   - hypothesis generator
   - statistical critic
   - clinical critic
   - methodological critic
   - experiment supervisor
4. Write JSON to `host_outputs/round_XXX_result.json`.
5. Advance the run:

```bash
python -m neurooracle.src.hypothesis_cli host-agent-next --run-dir neurooracle/data/host_agent_runs/case1
```

Check state:

```bash
python -m neurooracle.src.hypothesis_cli host-agent-status --run-dir neurooracle/data/host_agent_runs/case1
```

## Required Result Shape

The task file includes `expected_result_template`. Keep the same top-level keys:

- `schema_version`
- `task_id`
- `round`
- `status`
- `hypotheses`
- `critic_review`
- `experiment_plan`
- `result_supervision`
- `next_round`

Use `status=complete` or `next_round.decision=stop` to end successfully. Use
`status=blocked` or `next_round.decision=blocked` only when the run cannot make
meaningful progress without missing data, missing tools, or user policy input.

## Guardrails

- Do not fabricate graph edges, PubMed support, command outputs, NeuroBench
  scores, or experiment results.
- Preserve exact commands, checked artifacts, and failure reasons in the JSON.
- Prefer deterministic NeuroOracle and NeuroBench commands for evidence; use
  host-agent reasoning for synthesis, criticism, supervision, and next actions.
- Keep generated claims separate from the main KG unless the user explicitly
  asks for graph injection.
"""
    _write_generated(ref_dir / "host_agent_autoresearch.md", text)


def _write_model_workflows(ref_dir: Path) -> None:
    model_dirs = [
        p.name
        for p in sorted(MODELS_ROOT.iterdir())
        if p.is_dir() and not p.name.startswith("__")
    ] if MODELS_ROOT.exists() else []
    lines = [
        GENERATED_MARKER,
        "# NeuroClaw Model Workflow Reference",
        "",
        f"Models root: `{_repo_path(MODELS_ROOT)}`",
        "",
        "Use this reference for brain model training, evaluation, sweeps, and",
        "NeuroBench model-training tasks.",
        "",
        "Common entry points:",
        "",
        "```bash",
        "python models/train_unified.py --help",
        "python models/scripts/run_benchmark.py --help",
        "```",
        "",
        "Discovered model folders:",
        "",
    ]
    if model_dirs:
        lines.extend(f"- `{name}`" for name in model_dirs)
    else:
        lines.append("- No model folders discovered.")
    _write_generated(ref_dir / "model_workflows.md", "\n".join(lines) + "\n")


def _write_install_prompt_reference(ref_dir: Path) -> None:
    text = f"""{GENERATED_MARKER}
# NeuroClaw Host-Agent Installation Prompt

Use this reference when a user wants Codex, Claude Code, Cursor, OpenClaw,
Hermes, WorkBuddy, or QClaw to install NeuroClaw for them and then operate in
NeuroClaw mode.

## Copy-Paste Prompt For Codex / Claude Code

```text
Please install NeuroClaw on this machine and then install the NeuroClaw agent
integration for this host agent.

Repository: https://github.com/CUHK-AIM-Group/NeuroClaw
Preferred local path: <choose or ask me>
Target host agent: <codex | claude-code | cursor | openclaw | hermes | workbuddy | qclaw | all>

Before running the installer, inspect this machine and prepare the setup
answers. Do not guess silently. Use safe defaults when they are obvious, and ask
me only for missing information that cannot be discovered.

Discover or confirm:
1. Python runtime:
   - Find a real Python executable, not a broken launcher/alias.
   - Verify Python >= 3.10.
   - If conda/mamba exists, decide whether to use or create a `neuroclaw` env.
   - If Python is missing or unsuitable, ask whether to use conda or Docker.
2. Docker:
   - Check `docker --version` and whether Docker can run containers.
   - Use Docker only if I ask for it or local Python/toolchain setup is not
     suitable.
3. GPU/CUDA:
   - Check `nvidia-smi` and/or `nvcc --version`.
   - Record CPU-only if no GPU/CUDA is available.
4. Neuroimaging toolchain:
   - Check `FSLDIR`, `fsl`, and FSL `bin` path.
   - Check `FREESURFER_HOME` and `recon-all`.
   - Check `dcm2niix`.
   - Check optional MATLAB/SPM only if relevant.
   - Check whether fMRIPrep/QSIPrep should be run through Docker containers.
5. LLM backend:
   - Ask which provider to use if not already configured.
   - Supported provider choices include OpenAI, DeepSeek, MiniMax, Kimi/Moonshot,
     Qwen/DashScope, Baichuan, Zhipu GLM, Doubao/Ark, OpenRouter, Together,
     Groq, Fireworks, Ollama, llama.cpp, Anthropic, and local model.
   - Ask for the API key environment variable name, but do not print or store
     secrets unless I explicitly provide them for this session.
6. Data directories:
   - Ask for or choose default BIDS root and output root.
   - If I do not specify them, use `~/data/bids` and `~/data/outputs`.

Then install:
1. Clone or update the NeuroClaw repository.
2. Run the setup wizard or write `neuroclaw_environment.json` from the discovered
   answers.
3. Validate with `python installer/setup.py --check`.
4. Install the host-agent integration with:

   `python installer/install_agent_integration.py --target <target>`

5. Verify that the generated NeuroClaw skill/rule exists and that
   `references/skill_catalog.md`, `references/autoresearch.md`,
   `references/host_agent_autoresearch.md`, `references/neurobench_catalog.md`,
   and `references/model_workflows.md` were generated.
6. Tell me the exact Python executable, setup type, Docker choice, CUDA/GPU
   status, FSL path, FreeSurfer path, dcm2niix path, LLM provider, BIDS root,
   output root, and installed integration path.

After installation, enter NeuroClaw mode for neuroimaging and autoresearch
tasks.
```

## Minimal Local Install Commands

Use these after the setup information above is known:

```bash
git clone https://github.com/CUHK-AIM-Group/NeuroClaw.git
cd NeuroClaw
python installer/setup.py
python installer/setup.py --check
python installer/install_agent_integration.py --target codex
```

For all supported host agents:

```bash
python installer/install_agent_integration.py --target all
```

For manual import into a host agent with a custom location:

```bash
python installer/install_agent_integration.py --target all --export ./dist/agent-integrations
```

## Notes For Host Agents

- Prefer inspecting the machine first over asking the user a long questionnaire.
- Ask the user only for secrets, missing paths, or policy choices such as Docker
  versus local Python when the local state is ambiguous.
- Never claim NeuroClaw is installed until `installer/setup.py --check` passes
  or you clearly explain why it could not be run.
- A newly installed skill may require a new host-agent thread/session before it
  appears in the active skill list.
"""
    _write_generated(ref_dir / "install_prompt.md", text)


def _router_skill_text() -> str:
    return f"""---
name: neuroclaw
description: Use NeuroClaw for neuroimaging, BIDS, fMRI, DWI, sMRI, FreeSurfer, FSL, NeuroOracle, NeuroBench, brain model training, and autoresearch.
---

# NeuroClaw Mode

You are operating in NeuroClaw mode inside the host agent.

NeuroClaw is a neuroscience-first research agent for executable neuroimaging
workflows, reproducible model execution, NeuroOracle autoresearch, and
NeuroBench evaluation. Use the local NeuroClaw repository as the source of
domain capability:

`{_repo_path(REPO_ROOT)}`

## Identity

When this skill is active, behave as NeuroClaw:

- Focus on neuroimaging, BIDS, fMRI, DWI, sMRI, EEG/MEG, PET, FreeSurfer, FSL,
  fMRIPrep, QSIPrep, Nilearn, MNE, NeuroOracle, NeuroBench, and brain model
  execution.
- Prefer executable workflows and reproducible commands over abstract advice.
- Inspect generated catalogs before reading full source files.
- Use NeuroClaw skills and scripts as implementation references.
- Keep scientific claims grounded in data, graph evidence, or cited literature.

## Reference Order

1. Read `references/skill_catalog.md` to choose a workflow skill.
2. Read `references/install_prompt.md` when the user wants this host agent to
   install NeuroClaw or enter NeuroClaw mode from a fresh machine.
3. Read `references/autoresearch.md` for NeuroOracle and autoresearch.
4. Read `references/host_agent_autoresearch.md` when this host agent should use
   its own model as NeuroClaw's generator, critic, and experiment supervisor.
5. Read `references/neurobench_catalog.md` for benchmark tasks.
6. Read `references/model_workflows.md` for model training/evaluation.
7. Read the selected full `SKILL.md` or script from the NeuroClaw repository.

## Common Commands

```bash
python core/agent/main.py --web
python core/agent/main.py --benchmark
python core/agent/main.py --score-benchmark
bash neurooracle/run_case_study.sh case1_transdiagnostic
python -m neurooracle.src.hypothesis_cli host-agent-init case1_transdiagnostic --output-dir neurooracle/data/host_agent_runs/case1 --max-rounds 5
python -m neurooracle.phase1
python -m neurooracle.phase2 --broad --max-workers 12
python installer/install_agent_integration.py --target codex
```

## Guardrails

- Do not read every NeuroClaw skill at once. Use the catalog and then inspect the
  narrow skill needed for the user task.
- Do not claim a pipeline has run unless commands were actually executed and
  outputs were checked.
- For long jobs, state expected inputs, outputs, and runtime assumptions first.
- If external datasets, licensed tools, API keys, or large compute are missing,
  say exactly what is missing and provide the closest reproducible dry-run path.
- If asked to install NeuroClaw, first inspect Python, Docker, CUDA/GPU, FSL,
  FreeSurfer, dcm2niix, LLM provider/API-key environment variable, BIDS root,
  and output root. Use `references/install_prompt.md` as the checklist.
- If asked to use this host agent's built-in model for autoresearch, use
  `references/host_agent_autoresearch.md` and the host-agent JSON loop. Do not
  route that work through NeuroClaw's configured LLM API unless requested.
"""


def _write_generated(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _install_root(target: str, scope: str) -> Path:
    if target == "codex":
        base = Path.home() / ".codex" if scope == "user" else REPO_ROOT / ".codex"
    elif target == "claude-code":
        base = Path.home() / ".claude" if scope == "user" else REPO_ROOT / ".claude"
    elif target == "cursor":
        base = Path.home() / ".cursor" if scope == "user" else REPO_ROOT / ".cursor"
        return base / "rules"
    elif target == "openclaw":
        base = Path.home() / ".openclaw" if scope == "user" else REPO_ROOT / ".openclaw"
    elif target == "hermes":
        base = Path.home() / ".hermes" if scope == "user" else REPO_ROOT / ".hermes"
    elif target == "workbuddy":
        base = Path.home() / ".workbuddy" if scope == "user" else REPO_ROOT / ".workbuddy"
    elif target == "qclaw":
        base = Path.home() / ".qclaw" if scope == "user" else REPO_ROOT / ".qclaw"
    else:
        raise ValueError(f"Unknown target: {target}")
    return base / "skills" / "neuroclaw"


def _cursor_rule_text(ref_dir: Path) -> str:
    return f"""---
description: NeuroClaw mode for neuroimaging, NeuroOracle, NeuroBench, model workflows, and autoresearch.
globs:
  - "**/*"
alwaysApply: false
---

# NeuroClaw Mode

Use NeuroClaw mode when the task involves neuroimaging, BIDS, fMRI, DWI, sMRI,
FreeSurfer, FSL, fMRIPrep, QSIPrep, Nilearn, MNE, NeuroOracle, NeuroBench,
brain model training, or autoresearch.

NeuroClaw repository:

`{_repo_path(REPO_ROOT)}`

Before reading the full repository, inspect the generated references:

- `{_repo_path(ref_dir / "skill_catalog.md")}`
- `{_repo_path(ref_dir / "install_prompt.md")}`
- `{_repo_path(ref_dir / "autoresearch.md")}`
- `{_repo_path(ref_dir / "host_agent_autoresearch.md")}`
- `{_repo_path(ref_dir / "neurobench_catalog.md")}`
- `{_repo_path(ref_dir / "model_workflows.md")}`

Behave as NeuroClaw: prioritize executable, reproducible neuroimaging workflows;
use NeuroClaw skills and scripts as implementation references; keep scientific
claims grounded in data, graph evidence, or cited literature; and do not claim a
pipeline has run unless commands were executed and outputs were checked.
"""


def _install_skill(target: str, scope: str) -> Path:
    root = _install_root(target, scope)
    if target == "cursor":
        ref_dir = root / "neuroclaw-references"
        root.mkdir(parents=True, exist_ok=True)
        _write_generated(root / "neuroclaw.mdc", _cursor_rule_text(ref_dir))
        _write_skill_catalog(ref_dir)
        _write_install_prompt_reference(ref_dir)
        _write_neurobench_catalog(ref_dir)
        _write_autoresearch_reference(ref_dir)
        _write_host_agent_autoresearch_reference(ref_dir)
        _write_model_workflows(ref_dir)
        return root

    ref_dir = root / "references"
    root.mkdir(parents=True, exist_ok=True)
    _write_generated(root / "SKILL.md", _router_skill_text())
    _write_skill_catalog(ref_dir)
    _write_install_prompt_reference(ref_dir)
    _write_neurobench_catalog(ref_dir)
    _write_autoresearch_reference(ref_dir)
    _write_host_agent_autoresearch_reference(ref_dir)
    _write_model_workflows(ref_dir)
    return root


def _append_persona_default(target: str, scope: str) -> Path | None:
    if scope != "user":
        return None
    if target == "claude-code":
        memory_path = Path.home() / ".claude" / "CLAUDE.md"
    elif target == "codex":
        memory_path = Path.home() / ".codex" / "NEUROCLAW.md"
    else:
        return None
    memory_path.parent.mkdir(parents=True, exist_ok=True)
    block = (
        "\n"
        f"{GENERATED_MARKER}\n"
        "For neuroscience, neuroimaging, BIDS, NeuroOracle, NeuroBench, brain model "
        "training, and autoresearch tasks, use the installed NeuroClaw skill and "
        "operate in NeuroClaw mode.\n"
    )
    existing = _read_text(memory_path)
    if "operate in NeuroClaw mode" not in existing:
        with memory_path.open("a", encoding="utf-8") as f:
            f.write(block)
    return memory_path


def _copy_to_output(path: Path, output: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    shutil.copytree(path, output)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install NeuroClaw as an external-agent skill pack.",
    )
    parser.add_argument(
        "--target",
        choices=[*AGENT_TARGETS, "both", "all"],
        default="both",
        help="Host agent to install into.",
    )
    parser.add_argument(
        "--scope",
        choices=["user", "project"],
        default="user",
        help="Install into user home or this repository.",
    )
    parser.add_argument(
        "--persona-default",
        action="store_true",
        help="Add a small persistent NeuroClaw-mode hint where the host supports it.",
    )
    parser.add_argument(
        "--export",
        type=Path,
        default=None,
        help="Copy the generated skill pack to this directory after installation.",
    )
    args = parser.parse_args()

    if args.target == "both":
        targets = ["codex", "claude-code"]
    elif args.target == "all":
        targets = list(AGENT_TARGETS)
    else:
        targets = [args.target]
    installed: list[tuple[str, Path]] = []
    for target in targets:
        path = _install_skill(target, args.scope)
        installed.append((target, path))
        print(f"Installed NeuroClaw skill for {target}: {path}")
        if args.persona_default:
            memory_path = _append_persona_default(target, args.scope)
            if memory_path is not None:
                print(f"Updated persona hint for {target}: {memory_path}")

    if args.export is not None:
        export_root = args.export.resolve()
        export_root.mkdir(parents=True, exist_ok=True)
        for target, path in installed:
            _copy_to_output(path, export_root / target / "neuroclaw")
        print(f"Exported generated skill packs to: {export_root}")


if __name__ == "__main__":
    main()
